#!/bin/sh

# traccar user setup
exists=false
getent passwd traccar >/dev/null 2>&1 && exists=true

if ! $exists; then
    printf "Creating user traccar... "
    useradd -b /var/lib/traccar -d /var/lib/traccar -U traccar && printf "OK\n" || printf "FAILED\n"
fi

printf "Fixing user rights... "
chown -R traccar /var/lib/traccar /var/log/traccar && printf "OK\n" || printf "FAILED (1/2)\n"

echo "Starting supervisor services..."
supervisorctl reread
supervisorctl update
supervisorctl restart "traccar:*"

if [ -x /usr/sbin/ufw ]; then
  echo "Appling UFW rules..."
  /usr/bin/traccar_ufw_setup enable
fi
